# Numpy - Numerical Python

advantages of numpy arrays:
1. allows several mathematical operations
2. Fatser operations


In [79]:
import numpy as np

List vs numpy - Time taken

In [80]:
from time import process_time

Time taken by a list

In [81]:
python_list = [i for i in range(1000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0


In [82]:

np_array = np.array([ i for i in range(1000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0


# Numpy arrays

In [83]:
# list 
list1 = [1,2,3,4,5]
print(list1)
type(list1)


[1, 2, 3, 4, 5]


list

In [84]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [85]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [86]:
a.shape

(4,)

In [87]:

b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [88]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy arrays

In [89]:
# create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [90]:
#  create a numpy array of ones
y = np.ones((2,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [91]:
# array of a particular value
z = np.full((4,6),5)
print(z)

[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]


In [92]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [93]:
# creating a array with random values 
b = np.random.random((3,4))
print(b)


[[0.14507744 0.53232316 0.31048361 0.80796162]
 [0.02481497 0.62253631 0.67264341 0.0022575 ]
 [0.81097416 0.75460824 0.15018692 0.15939862]]


In [94]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)


[10. 15. 20. 25. 30.]


In [95]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [96]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [97]:
c = np.random.randint(10,90,(5,5))
print(c)

[[60 17 75 70 68]
 [73 20 34 31 27]
 [16 10 52 19 54]
 [40 26 87 75 37]
 [46 27 65 46 33]]


In [98]:
# array dimension
c.shape


(5, 5)

In [99]:
# number of dimension
print(c.ndim)

2


In [100]:
# number of elements in an array
print(c.size)

25


In [101]:
# checking the data type of the values in the array
print(c.dtype)

int32


#### Mathematical operations on a np array

In [102]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [103]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [104]:
print(a)
print(b)

[[4 0 2]
 [6 3 7]
 [5 6 1]]
[[11 15 12]
 [19 10 10]
 [16 12 10]]


In [105]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[15 15 14]
 [25 13 17]
 [21 18 11]]
[[ -7 -15 -10]
 [-13  -7  -3]
 [-11  -6  -9]]
[[ 44   0  24]
 [114  30  70]
 [ 80  72  10]]
[[0.36363636 0.         0.16666667]
 [0.31578947 0.3        0.7       ]
 [0.3125     0.5        0.1       ]]


In [106]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [107]:
print(a)
print(b)

[[6 8 9]
 [0 9 5]
 [8 1 4]]
[[17 15 18]
 [16 15 15]
 [18 15 11]]


In [108]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[23 23 27]
 [16 24 20]
 [26 16 15]]
[[-11  -7  -9]
 [-16  -6 -10]
 [-10 -14  -7]]
[[102 120 162]
 [  0 135  75]
 [144  15  44]]
[[0.35294118 0.53333333 0.5       ]
 [0.         0.6        0.33333333]
 [0.44444444 0.06666667 0.36363636]]


#### Array manipulation

In [109]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 4 4]
 [2 3 8]]
(2, 3)


In [110]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[6 2]
 [4 3]
 [4 8]]
(3, 2)


In [111]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 3 0]
 [8 4 7]]
(2, 3)


In [112]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[7 8]
 [3 4]
 [0 7]]
(3, 2)


In [113]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 9 8]
 [1 9 7]]
(2, 3)


In [114]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 9]
 [8 1]
 [9 7]]
(3, 2)
